config/routes.rb
Rails.application.routes.draw do
  get 'new' => 'books#new'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as:'book'

  get 'books/:id/edit' => 'books#edit', as: 'edit_book'

  root to: 'homes#top'
  get '/books' => 'books#index'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
　　@book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
    flash[:notice]="Book was successfully created."
    redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if   @book.update(book_params)
    flash[:notice]="Book was successfully created."
    redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<div>
    <%= flash[:notice] %>
</div>


<h1>Editing Books</h1>

<% if @book.errors.any? %>
    <h2><%= @book.errors.count %> errors prohibited this book from being saved</h2>

    <ul>
     <% @book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
    </ul>
  <% end %>

<div class="form">
  <%= form_with model: @book, url:update_book_path(@book.id), method: :patch do |f| %>

      <label for="book_title">Title</label><br>
      <%= f.text_field :title %><br>

      <label for="book_body">Body</label><br>
      <%= f.text_area :body %><br>

      <%= f.submit 'Update Book' %>
  <% end %>
 </div>


 <%= link_to "Show", book_path(@book.id) %> |
 <a class="back" href="/books">Back</a>

app/views/books/index.html.erb
<h1>Books</h1>

  <table>
      <thead>
       <th>Title</th>
       <th>Body</th>
       <th colspan="3"></th>
      </thead>

      <tbody>
       <% @books.each do |book| %>
       <tr>
       <td><%= book.title %></td>
       <td><%= book.body %></td>
       <td><%= link_to "Show", book_path(book.id) %></td>
       <td><%= link_to "Edit", edit_book_path(book.id) %></td>
       <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
       </tr>
       <% end %>
      </tbody>

   </table>


  <h2>New book</h2>

  <% if @book.errors.any? %>
    <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>

    <ul>
     <% @book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
    </ul>
  <% end %>

 <div class="form">
  <%= form_with model: @book, url: '/books',  method: :post do |f| %>

      <label for="book_title">Title</label><br>
      <%= f.text_field :title %><br>

      <label for="book_body">Body</label><br>
      <%= f.text_area :body %><br>

      <%= f.submit 'Create Book' %>
  <% end %>
 </div>

app/views/books/new.html.erb
<% if @book.errors.any? %>
    <%= @book.errors.count %>prohibited this book from being saved

    <ul>
     <% @book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
    </ul>
  <% end %>

app/views/books/show.html.erb
<div>
    <%= flash[:notice] %>
</div>

<body>
<p id="notice"></p>
<strong>Title:</strong>
<p><%= @book.title %></p>

<strong>Body:</strong>
<p><%= @book.body %></p>


<%= link_to "Edit", edit_book_path(@book.id) %> |
<a class="back" href="/books">Back</a>



</body>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html>
 <head>
   <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
 </head>

 <body>
  <h1>ようこそ <strong>Bookers</strong> へ！</h1>
  <div class=text>

    <div class=text1>
     <p><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や</p>
    </div>

    <div class=text2>
  　  <p>印象を共有し交換することができます</p>
  　</div>

  　<div class=text3>
 　  <p><a href="/books">start</a></p>
    </div>
    
 　</div>
 </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebCampBackendNew</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>